feat: first version of citation
HTL3R-Typst/htl3r-da pull request #47
Opened 2024-12-29 00:21 UTC by sidious38

2024-12-29 00:28 UTC, kre9 requested changes

2024-12-29 00:28 UTC, kre9 commented on src/lib/assets/harvard-htl3r.csl
> +    <rights license="http://creativecommons.org/licenses/by-sa/3.0/">This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 License</rights>
Not compatible with the 0-BSD licence.

2024-12-29 17:28 UTC, Davideko212 commented
Beim Zugriffsdatum fehlen die Punkte, soll das so sein?
![image](https://github.com/user-attachments/assets/c71e314d-037c-4a2f-b94e-924bec722996)

2024-12-29 18:29 UTC, sidious38 commented
> Beim Zugriffsdatum fehlen die Punkte, soll das so sein? 
@Davideko212 ja, siehe Spezifikation in der Word-Vorlage. Mir gefällts auch nicht, aber ist halt so.

CSL war absichtlich noch nicht implementiert, siehe Kommentar von Viktor. Wir müssen uns anscheinend noch eine Variante überlegen, wo wir den Citation-Style manuell einbinden, da sonst die Licenses violated werden.

2024-12-29 20:18 UTC, kre9 requested changes
Lizenzthematik ist noch offen + Unterschied zwischen direkter/indirekter Zitation fehlt noch soweit ich sehe.

2024-12-29 20:18 UTC, kre9 commented on src/lib/util.typ
> +      style: "assets/harvard-htl3r.csl",
Wozu die extra Funktion? Sollte man den Style nicht eher in der Bibliography Page setzen?

2024-12-29 20:18 UTC, kre9 commented on src/lib/pages/bibliography.typ
> +    bibliography
Style könnte gleich hier gesetzt werden.

2025-01-03 08:17 UTC, cauvmou commented
Indirekte Zitierung ist somit mal implementiert, ich habe es halbwegs modular gemacht, sodass auch in Zukunft noch zusätzliche Zitiervarianten implementiert werden können.

Beispiel:
```typst
Das Linux-Server-Image wird mittels Cloud-Init, einer plattformübergreifenden Software für das Aufsetzen von 
Cloudinstanzen, welche sich als Industriestandard etabliert hat @ci-docs[comp], aufgesetzt.

Das Linux-Server-Image wird mittels Cloud-Init, einer plattformübergreifenden Software für das Aufsetzen von 
Cloudinstanzen, welche sich als Industriestandard etabliert hat @ci-docs[#htl3r.comp], aufgesetzt.

Das Linux-Server-Image wird mittels Cloud-Init, einer plattformübergreifenden Software für das Aufsetzen von 
Cloudinstanzen, welche sich als Industriestandard etabliert hat @ci-docs[#htl3r.comp[S. 12]], aufgesetzt.
```
![image](https://github.com/user-attachments/assets/be785e0e-552a-4bf8-bef9-2748a8394da8)

2025-01-03 10:41 UTC, cauvmou commented
Es gab ein paar Änderungen welche die Formatierung betreffen, jedoch nichts alt zu großes.

Beispiel:
```typst
Das Linux-Server-Image wird mittels Cloud-Init, einer plattformübergreifenden Software für das Aufsetzen von 
Cloudinstanzen, welche sich als Industriestandard etabliert hat @ci-docs[comp], aufgesetzt.

Das Linux-Server-Image wird mittels Cloud-Init, einer plattformübergreifenden Software für das Aufsetzen von 
Cloudinstanzen, welche sich als Industriestandard etabliert hat @ci-docs[#htl3r.comp], aufgesetzt.

Das Linux-Server-Image wird mittels Cloud-Init, einer plattformübergreifenden Software für das Aufsetzen von 
Cloudinstanzen, welche sich als Industriestandard etabliert hat @ci-docs[#htl3r.comp[S. 12]], aufgesetzt.
```
![image](https://github.com/user-attachments/assets/a8fdacd3-3d82-46f2-9781-fbc2bd6e2923)

2025-01-03 10:44 UTC, cauvmou commented on src/lib/pages/bibliography.typ
> +    bibliography
Styling wird jetzt direkt in der Templatefunktion gesetzt. Keine weiterer BS nötig.

2025-01-03 10:46 UTC, cauvmou commented on src/lib/util.typ
> +      style: "assets/harvard-htl3r.csl",
Doch geht und wurde von mir implementiert.

2025-01-03 12:51 UTC, Davideko212 approved these changes
schaut supi aus aber viktor muss noch lizenz machen

2025-01-03 19:21 UTC, kre9 approved these changes
Vielen Dank!

2025-01-03 19:23 UTC, kre9 commented
Licencing Status-Quo:

Das CSL-File wird mit CC-BY-SA-4.0 lizensiert und bleibt in dem Repo. 

Mal schauen, ob das als Typst-Package so akzeptiert wird. Laut den Packaging-Guidelines wäre das nicht erlaubt. ("license: The package's license. Must contain a valid SPDX-2 expression describing one or multiple OSI-approved licenses.")
Siehe: https://github.com/typst/packages/issues/1511

 @cauvmou bitte absegnen

2025-01-03 23:01 UTC, cauvmou approved these changes

2025-01-03 23:01 UTC, merged